#ifndef __OBLFR_COURIER_H__
#define __OBLFR_COURIER_H__

#include <stdint.h>
#include <stdbool.h>

#include "oblfr_common.h"
#include "sdkconfig.h"

/* Peripheral device ID */
enum m0_interrupt_source_e {
  BFLB_IPC_DEVICE_SDHCI,
  BFLB_IPC_DEVICE_UART2,
  BLFB_IPC_DEVICE_USB,
  BFLB_IPC_DEVICE_EMAC,
  BFLB_IPC_DEVICE_GPIO,
  BFLB_IPC_DEVICE_MBOX_TX,
  BFLB_IPC_DEVICE_MBOX_RX,
  BFLB_IPC_DEVICE_DMA0_ALL,
  BFLB_IPC_DEVICE_DMA1_ALL,
  BFLB_IPC_DEVICE_IRTX,
  BFLB_IPC_DEVICE_IRRX,
  BFLB_IPC_DEVICE_GPADC_DMA,
  BFLB_IPC_DEVICE_SPI0,
  BFLB_IPC_DEVICE_UART0,
  BFLB_IPC_DEVICE_UART1,
  BFLB_IPC_DEVICE_GPIO_DMA,
  BFLB_IPC_DEVICE_I2C0,
  BFLB_IPC_DEVICE_I2C1,
  BFLB_IPC_DEVICE_PWM,
  BFLB_IPC_DEVICE_TIMER0_CH0,
  BFLB_IPC_DEVICE_TIMER0_CH1,
  BFLB_IPC_DEVICE_TIMER0_WDT,
  BFLB_IPC_DEVICE_I2S,
  BFLB_IPC_DEVICE_PDS_WAKEUP,
  BFLB_IPC_DEVICE_HBN_OUT0,
  BFLB_IPC_DEVICE_HBN_OUT1
};

#define IPC_IRQn_MASK 0xff // bits 0-7
#define IPC_INT_SIG_SHIFT 8
#define IPC_INT_ENABLE_SIG_SHIFT 9

oblfr_err_t oblfr_mailbox_nuttx_init(void);
#endif
